name: JCore
author: SirSwiperlpp
version: '1.0'
main: de.sirswiperlpp.jcore.Main.Main
api-version: '1.20'

commands:
  ban:
    permission: jcore.admin.ban
    description: a command to ban players
  kick:
    permission: jcore.admin.ban
    description: a command to kick players
  tpa:
    permission: tpa.use
    description: a command to request Teleports
  spawn:
    permission: spawn.use
    description: Spawn Command
  home:
    permission: home.use
    description: Home Command
  sethome:
    permission: home.set.use
    description: Set Home Commnad
  delhome:
    permission: home.del.use
    description: Del Home Command
  vanish:
    permission: vanish.admin
    description: Vanish Command

permissions:
  jcore.admin.ban:
    description: permission for ban command
    default: op
  jcore.admin.kick:
    description: permssion for kick command
    default: op
  tpa.use:
    description: perm for tpa command
    default: true
  spawn.use:
    default: true
  home.use:
    default: true
  home.set.use:
    default: true
  home.del.use:
    default: true
  vanish.admin:
    default: op